### ISSUE TITLE
All Browsers - No error handling on page 1 of donation form

### ISSUE THREAD

**Issue by rdewagan** [convio/make-a-wish-luminate-framework#36] opened 2015-08-17 15:23 UTC
There seems to be no error handling on the first page of the donation form. This may be intended functionality but I wanted to still call it out. 

Steps to Reproduce:

1.) Start at http://wishdev.convio.net/site/PageServer?pagename=donate_now
2.) Select donation amount, then select "Donate in Honor or Memory
3.) Select "Thank you" card design 
4.) Leave "send card to" fields all blank. 
5.) Click save and continue at end of form. 

Intended functionality: You would not be able to proceed to the next page without these fields filled in.

**Comment by rdewagan** [comment] 2015-08-17 15:34
This may be taken care of in Issue #33

**Comment by noahcooper** [comment] 2015-08-18 18:28
Fixed.

**Comment by rdewagan** [comment] 2015-08-19 01:46
@noahcooper One more to check on here....

Steps to reproduce: 

1.) Go through donation form and select "donate in honor and memory" 
2.) Leave gift type and card type as preselected values 
3.) Do not select card design 
4.) Enter in "send card to" info 
5.) Click save and continue 

Should we have an error on this page as the user did not select a card design ?

**Comment by noahcooper** [comment] 2015-08-20 08:19
Closing this as a duplicate of issue #33.

**Closed by noahcooper** 2015-08-20 08:19 UTC
